site_name: База знаний
site_url: https://ttenushko.github.io/personal-wiki/
docs_dir: site-src

theme:
  name: material
  language: ru
  palette:
    - scheme: default
      toggle:
        icon: material/weather-night
        name: Тёмная тема
    - scheme: slate
      toggle:
        icon: material/weather-sunny
        name: Светлая тема
  features:
    - navigation.sections
    - navigation.expand
    - navigation.indexes
    - search.suggest
    - search.highlight

plugins:
  - search:
      lang: ru

extra_css:
  - extra.249775b0.css

extra:
  generator: false


extra_javascript:
  - inline-search.a30d2a2b.js
  - tags-data.b098b713.js

nav:
- Главная: index.md
- Личное: personal/index.md
- Разработка: dev/index.md
- Автомобили: auto/index.md
